set(SOURCES
	src/ankerl/unordered_dense.h
	src/BSResource.h
	src/BSResource.cpp
	src/BSTexture.h
	src/BSTexture.cpp
	src/BSScaleformImageLoader.h
	src/BSScaleformImageLoader.cpp
	src/PCH.h
	src/main.cpp
)
